services:
  - type: web
    name: rustdesk-argo
    env: docker
    plan: free

    envVars:
      - key: CF_TUNNEL_TOKEN
        sync: false
      - key: ALWAYS_USE_RELAY
        value: "Y"

    autoDeploy: true
